Auto <- read.csv("/home/beeps/rtmp/external/eco/noce/islr/labs/3/data/auto.csv", header=T, na.strings="?")
Auto <- na.omit(Auto)
lm.ols <- lm(mpg ~ horsepower, data=Auto)
summary(lm.ols)
confint(lm.ols)
par(mfrow=c(2,2))
plot(lm.ols)
